### ISSUE TITLE
Messages not selectable

### ISSUE THREAD

**Issue by luandro** [staltz/mmmmm-mobile#57] opened 2018-05-25 12:46 UTC
**Expected behavior:**
Should be able to copy and paste messages.

**Actual behavior:**
Text isn't selectable.

**Technical details**
Maybe a problem with Markdown renderer?

- MMMMM app version: 0.13-alpha
- Device/phone model: Samsung S7 Edge
- Android OS version: 7.0

**Comment by staltz** [comment] 2018-05-25 13:01
Duplicate of #52 

Will release this in a new version soon

**Closed by staltz** 2018-05-25 13:01 UTC
